import { EventQueue } from "../events/event-queue"
import { Player } from "./player";

export interface GameContext {
    player: Player;
    // players..
    // rocks...
    // wrecks...
    // projectiles...
    // etc...
    eventQueue: EventQueue;
    log: (msg: string) => void;
}