name: Typecheck & Lint & Test

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]

concurrency:
  cancel-in-progress: true
  group: lint-${{ github.ref }}

jobs:
  typecheck_lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
      - run: npm ci --audit=false
      - run: npm run lint
      - run: npm run typecheck:all
      - run: npm run test:all
